site_name: Personal Knowledge Base
site_description: Engineering, DSP, and Embedded Systems Notes
site_author: Your Name
site_url: https://<username>.github.io/dsp-basics-kb/

theme:
  name: readthedocs
  language: en

markdown_extensions:

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
